*&---------------------------------------------------------------------*
*& Include          ZDM_INWARD_GENERATOR_TOP
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&  Include           ZGSP_INWARD_GENERATOR_TOP
*&---------------------------------------------------------------------*
TABLES: bsis,bseg,bkpf,j_1it030k.
TYPE-POOLS slis.
DATA : it_fcat TYPE slis_t_fieldcat_alv . "field catalog table
DATA : wa_fcat       LIKE LINE OF it_fcat , "field catalog work area
       gs_str_layout TYPE slis_layout_alv.
DATA: lt_header     TYPE slis_t_listheader,
      wa_header     TYPE slis_listheader,
      ls_header     TYPE slis_listheader,
      t_line        LIKE wa_header-info,
      ld_lines      TYPE i,
      ld_linesc(10) TYPE c.
DATA : l_var_cnt  TYPE i,
       l_var_text TYPE string.

DATA : it_listheader TYPE slis_t_listheader,
       wa_listheader TYPE slis_listheader.
DATA: l_tab_doctype         TYPE TABLE OF zdmdoctype,
      l_str_doctype         TYPE zdmdoctype,
      l_tab_bus_id          TYPE TABLE OF zei_bus_id,
      l_str_bus_id          TYPE zei_bus_id,
      l_str_final           TYPE zdm_global,
      l_tab_bus_unit_id     TYPE TABLE OF zei_bus_unit_id,
      l_str_bus_unit_id     TYPE zei_bus_unit_id,
      l_str_cust_data       TYPE zei_cust_data,
      l_tab_zei_uom_maping  TYPE TABLE OF zei_uom_maping,
      l_str_zei_uom_maping  TYPE zei_uom_maping,
      l_tab_zgst_state_code TYPE TABLE OF zei_state_code,
      l_str_zgst_state_code TYPE zei_state_code.

TYPES: BEGIN OF ty_rbkp,
         xblnr TYPE rbkp-xblnr,
         bukrs TYPE bukrs,
         belnr TYPE rbkp-belnr,
         gjahr TYPE rbkp-gjahr,
         budat TYPE rbkp-budat,
         bldat TYPE bldat,
         blart TYPE rbkp-blart,
         bupla TYPE rbkp-bupla,
         stblg TYPE rbkp-stblg,
       END OF ty_rbkp.

TYPES: BEGIN OF ty_rseg,
         belnr       TYPE rseg-belnr,
         gjahr       TYPE rseg-gjahr,
         buzei       TYPE rseg-buzei,
         ebeln       TYPE rseg-ebeln,
         ebelp       TYPE rseg-ebelp,
         zekkn       TYPE rseg-zekkn,
         matnr       TYPE rseg-matnr,
         bukrs       TYPE rseg-bukrs,
         werks       TYPE rseg-werks,
         wrbtr       TYPE rseg-wrbtr,
         shkzg       TYPE rseg-shkzg,
         mwskz       TYPE rseg-mwskz,
         menge       TYPE rseg-menge,
         bstme       TYPE rseg-bstme,
         pstyp       TYPE rseg-pstyp,
         bklas       TYPE rseg-bklas,
         tbtkz       TYPE rseg-tbtkz,
         lfbnr       TYPE rseg-lfbnr,
         lfgja       TYPE rseg-lfgja,
         lifnr       TYPE rseg-lifnr,
         customs_val TYPE rseg-customs_val,
       END OF ty_rseg.

TYPES: BEGIN OF ty_lfa1,
         lifnr TYPE lfa1-lifnr,
         land1 TYPE lfa1-land1,
         name1 TYPE lfa1-name1,
         name2 TYPE lfa1-name2,
         name3 TYPE lfa1-name3,
         name4 TYPE lfa1-name4,
         ort01 TYPE lfa1-ort01,
         regio TYPE lfa1-regio,
         stceg TYPE lfa1-stceg,
         stcd3 TYPE lfa1-stcd3,
         adrnr TYPE lfa1-adrnr,
       END OF ty_lfa1.

TYPES : BEGIN OF ty_adrc,
          addrnumber TYPE adrc-addrnumber,
          name3      TYPE adrc-name3,
        END OF ty_adrc.

TYPES:BEGIN OF ty_j_1bbranch,
        bukrs  TYPE j_1bbranch-bukrs,
        branch TYPE j_1bbranch-branch,
        gstin  TYPE j_1bbranch-gstin,
        name   TYPE j_1bbranch-name,
      END OF ty_j_1bbranch.

TYPES: BEGIN OF ty_ekko,
         ebeln TYPE ekko-ebeln,
         bedat TYPE ekko-bedat,
         bsart TYPE esart,
       END OF ty_ekko.

TYPES: BEGIN OF ty_mkpf,
         mblnr TYPE mkpf-mblnr,
         mjahr TYPE mkpf-mjahr,
         budat TYPE mkpf-budat,
       END OF ty_mkpf.

TYPES: BEGIN OF ty_ekpo,
         ebeln   TYPE ekpo-ebeln,
         ebelp   TYPE ekpo-ebelp,
         knttp   TYPE ekpo-knttp,
         txz01   TYPE ekpo-txz01,
         matnr   TYPE ekpo-matnr,
         j_1bnbm TYPE ekpo-j_1bnbm,
         iprkz   TYPE ekpo-iprkz,
       END OF ty_ekpo.

TYPES: BEGIN OF ty_bset,
         bukrs TYPE bukrs,
         belnr TYPE belnr_d,
         gjahr TYPE gjahr,

         txgrp TYPE txgrp,
         buzei TYPE buzei,
         shkzg TYPE shkzg,
         fwbas TYPE fwbas_bses,
         fwste TYPE fwste,
         kschl TYPE kschl,
         kbetr TYPE kbetr_tax,
         mwskz TYPE bset-mwskz,
         hkont TYPE hkont,
       END OF ty_bset.

TYPES: BEGIN OF ty_awkey,
         belnr TYPE rbkp-belnr,
         awkey TYPE bkpf-awkey,
       END OF ty_awkey.

TYPES: BEGIN OF ty_bkpf,
         bukrs     TYPE bkpf-bukrs,
         belnr     TYPE bkpf-belnr,
         gjahr     TYPE bkpf-gjahr,
         monat     TYPE bkpf-monat,
         waers     TYPE bkpf-waers,
         awkey     TYPE bkpf-awkey,
         xblnr     TYPE bkpf-xblnr,
         budat     TYPE bkpf-budat,
         bldat     TYPE bkpf-bldat,
         blart     TYPE bkpf-blart,
         kursf     TYPE bkpf-kursf,
         awtyp     TYPE bkpf-awtyp,
         xreversal TYPE bkpf-xreversal,
         tcode     TYPE tcode,
       END OF ty_bkpf.

TYPES: BEGIN OF ty_rbkp_temp,
         xblnr TYPE rbkp-xblnr,
         bukrs TYPE bukrs,
         belnr TYPE rbkp-belnr,
         gjahr TYPE rbkp-gjahr,
         budat TYPE rbkp-budat,
         bldat TYPE bldat,
         blart TYPE rbkp-blart,
         stblg TYPE stblg,
         "xblnr TYPE xblnr,
       END OF ty_rbkp_temp.
TYPES : BEGIN OF ty_makt,
        matnr TYPE makt-matnr,
        maktx  TYPE makt-maktx,
  END OF ty_makt.

TYPES: BEGIN OF ty_bseg,
         bukrs   TYPE bseg-bukrs,
         belnr   TYPE bseg-belnr,
         gjahr   TYPE bseg-gjahr,
         buzei   TYPE bseg-buzei,
         buzid   TYPE bseg-buzid,
         koart   TYPE bseg-koart,
         mwskz   TYPE bseg-mwskz,
         txgrp   TYPE bseg-txgrp,
         ktosl   TYPE bseg-ktosl,
         matnr   TYPE bseg-matnr,
         werks   TYPE bseg-werks,
         menge   TYPE bseg-menge,
         meins   TYPE bseg-meins,
         bustw   TYPE bseg-bustw,
         taxps   TYPE bseg-taxps,
         bupla   TYPE bseg-bupla,
         lifnr   TYPE bseg-lifnr,
         zuonr   TYPE bseg-zuonr,
         hsn_sac TYPE bseg-hsn_sac,
       END OF ty_bseg.

TYPES: BEGIN OF ty_t001w,
         werks TYPE t001w-werks,
         name1 TYPE t001w-name1,
         regio TYPE t001w-regio,
       END OF ty_t001w.

TYPES: BEGIN OF ty_rseg_i,
         ebeln       TYPE rseg-ebeln,
         ebelp       TYPE rseg-ebelp,
         belnr       TYPE rseg-belnr,
         gjahr       TYPE rseg-gjahr,
         buzei       TYPE rseg-buzei,
         zekkn       TYPE rseg-zekkn,
         matnr       TYPE rseg-matnr,
         bukrs       TYPE rseg-bukrs,
         werks       TYPE rseg-werks,
         wrbtr       TYPE rseg-wrbtr,
         shkzg       TYPE rseg-shkzg,
         mwskz       TYPE rseg-mwskz,
         menge       TYPE rseg-menge,
         bstme       TYPE rseg-bstme,
         pstyp       TYPE rseg-pstyp,
         bklas       TYPE rseg-bklas,
         xekbz       TYPE rseg-xekbz,
         tbtkz       TYPE rseg-tbtkz,
         kschl       TYPE rseg-kschl,
         lfbnr       TYPE rseg-lfbnr,
         lfgja       TYPE rseg-lfgja,
         lifnr       TYPE rseg-lifnr,
         customs_val TYPE rseg-customs_val,
       END OF ty_rseg_i.

***Tables*************************************************************
DATA: l_tab_rbkp          TYPE STANDARD TABLE OF ty_rbkp,
      l_tab_rbkp_canc     TYPE STANDARD TABLE OF ty_rbkp,
      l_tab_rbkp_canc_cpy TYPE STANDARD TABLE OF ty_rbkp,
      l_tab_rseg          TYPE STANDARD TABLE OF ty_rseg,
      l_tab_rseg_i        TYPE STANDARD TABLE OF ty_rseg_i,
      l_tab_bkpf_i        TYPE STANDARD TABLE OF ty_bkpf,
      l_tab_bseg_i        TYPE STANDARD TABLE OF ty_bseg, " Import case.
      l_tab_lfa1          TYPE STANDARD TABLE OF ty_lfa1,
      l_tab_adrc          TYPE STANDARD TABLE OF ty_adrc,
      l_tab_lfa11         TYPE STANDARD TABLE OF ty_lfa1,
      l_tab_ekko          TYPE STANDARD TABLE OF ty_ekko,
      l_tab_t007s         TYPE STANDARD TABLE OF t007s,
      l_tab_mkpf          TYPE STANDARD TABLE OF ty_mkpf,
      l_tab_t001w         TYPE STANDARD TABLE OF ty_t001w,
      l_tab_j_1bbranch    TYPE STANDARD TABLE OF ty_j_1bbranch,
      l_tab_ekpo          TYPE STANDARD TABLE OF ty_ekpo,
      l_tab_bset          TYPE STANDARD TABLE OF ty_bset,
      l_tab_awkey         TYPE STANDARD TABLE OF ty_awkey,
      l_tab_bkpf          TYPE STANDARD TABLE OF ty_bkpf,
      l_tab_bseg          TYPE STANDARD TABLE OF ty_bseg,
         l_tab_bseg_matnr          TYPE STANDARD TABLE OF ty_bseg,
      L_tab_makt        TYPE STANDARD TABLE OF ty_makt,
      l_tab_bseg_lifnr    TYPE STANDARD TABLE OF ty_bseg,
      l_tab_bseg_menge    TYPE STANDARD TABLE OF ty_bseg,
      l_tab_bseg_hsn      TYPE STANDARD TABLE OF ty_bseg,
      l_tab_bseg1         TYPE STANDARD TABLE OF ty_bseg,
      l_tab_bseg_k        TYPE STANDARD TABLE OF ty_bseg,
      l_tab_bkpf_final    TYPE STANDARD TABLE OF ty_bkpf,

      l_tab_rbkp_temp     TYPE STANDARD TABLE OF ty_rbkp_temp.
*        L_TAB_B2B           TYPE STANDARD TABLE OF TY_OUT_FINAL.
***Structute**********************************************************
DATA : l_str_rbkp          TYPE ty_rbkp,
       l_Str_makt          TYPE ty_makt,
       l_str_rseg          TYPE ty_rseg,
       l_str_awkey         TYPE ty_awkey,
       l_str_bkpf_temp     TYPE ty_bkpf,
       l_str_rbkp_temp     TYPE ty_rbkp_temp,
       l_str_bkpf_final    TYPE ty_bkpf,
       l_str_lfa1          TYPE ty_lfa1,
       l_str_rseg_i        TYPE ty_rseg_i,
       l_str_bseg_i        TYPE ty_bseg,
       l_str_bseg_matnr   TYPE ty_bseg,
       l_str_bseg_hsn      TYPE ty_bseg,
       l_str_bseg_menge      TYPE ty_bseg,
       l_str_lfa11         TYPE ty_lfa1,
       l_str_rbkp_canc     TYPE ty_rbkp,
       l_str_adrc          TYPE ty_adrc,
       l_str_rbkp_canc_cpy TYPE ty_rbkp,
       l_str_ekko          TYPE ty_ekko,
       l_str_j_1bbranch    TYPE ty_j_1bbranch,
       l_str_t007s         TYPE t007s,
       l_str_mkpf          TYPE ty_mkpf,
       l_str_t001w         TYPE ty_t001w,
       l_str_ekpo          TYPE ty_ekpo,
       l_str_bset          TYPE ty_bset,
       l_str_bkpf          TYPE ty_bkpf,
       l_str_bseg          TYPE ty_bseg,
       l_str_bseg1         TYPE ty_bseg,
       l_str_bseg_lifnr    TYPE ty_bseg,
       l_str_bseg_k        TYPE ty_bseg,
       l_var_awkey         TYPE ty_awkey.
*         L_STR_FINAL         TYPE TY_OUT_FINAL.
FIELD-SYMBOLS : <fs_rbkp> TYPE ty_rbkp.

***Variables**********************************************************
DATA : l_var_tabix TYPE sy-tabix,
       v_imp       TYPE c,
       lv_matnr    TYPE mara-matnr,
       flag        TYPE i..
**********************************************************************




*TYPES: BEGIN OF TY_FINAL_INWARD_EY2.
**TYPES:  VEN_GST TYPE ZSUPPLIERGSTIN .    " " Supp Supplier GSTIN
**TYPES:  DOC_NO TYPE ZDOCUMENTNUMBER .   " Supp Invoice No
****TYPES:  DOC_DT TYPE ZDOCUMENTDATE .    " Supp Invoice Dt
**TYPES:  HSN_NO TYPE ZHSNORSAC .
**TYPES:  ITM_DESC TYPE ZITEMDESCRIPTION .
*TYPES:  ACC_DOC TYPE  BELNR_D.        " Acc Document No
**TYPES:  UOM TYPE ZUNITOFMEASUREMENT .
*TYPES:  MWSKZ TYPE MWSKZ.
*
**        INCLUDE STRUCTURE YGSTINWARD01.
*TYPES:END OF TY_FINAL_INWARD_EY2.


TYPES: BEGIN OF ty_final_inward.
    INCLUDE STRUCTURE zdm_global.
TYPES: END OF ty_final_inward.
TYPES: BEGIN OF ty_final_inward1.
    INCLUDE STRUCTURE zdm_global.
TYPES: END OF ty_final_inward1,
tty_final_inward TYPE TABLE OF ty_final_inward.

*BEGIN OF TY_HEAD,
*  HEAD(4096) TYPE C,
*END OF TY_HEAD,
*TTY_HEAD TYPE TABLE OF TY_HEAD,
*TTY_DFIES TYPE TABLE OF DFIES.


*CONSTANTS: GC_DRIVE_ROOT TYPE STRING VALUE 'C:',
*GC_FILE_SEPARATOR TYPE STRING VALUE '/',
*GC_FOLDER_ROOT TYPE STRING VALUE 'INWARD SUPPLY',
*GC_FOLDER_UNPROCESSED TYPE STRING VALUE 'UNPROCESSED',
*GC_PATH_FOR_AL11 TYPE STRING VALUE '/sap/GSTData/OBD',
*
*GC_FOLDER_INWARD TYPE STRING VALUE 'INWARD SUPPLY MAIN',
*GC_FOLDER_ADVPAIDRCM TYPE STRING VALUE 'ADVANCE PAID RCM',
*GC_FOLDER_ADVADJRCM TYPE STRING VALUE 'ADVANCE ADJUSTED RCM',
*GC_FOLDER_ITCREVERSAL TYPE STRING VALUE 'ITC REVERSAL',
*GC_FOLDER_TDS TYPE STRING VALUE 'TDS',
*
*GC_CODE_INWARD TYPE STRING VALUE 'IPR',
*GC_CODE_ADVPAIDRCM TYPE STRING VALUE 'ARI',
*GC_CODE_ADVADJRCM TYPE STRING VALUE 'AAI',
*GC_CODE_ITCREVERSAL TYPE STRING VALUE 'ITC',
*GC_CODE_TDS TYPE STRING VALUE 'IRC',
*
*GC_TABLENAME_INWARD(30) VALUE 'GT_FINAL_INWARD',
*GC_STRUCTURE_INWARD(30) VALUE 'YGSTINWARD01_ST',
*GC_STRUCTURE_INWARD1(30) VALUE 'YGSTINWARD01_DIS',
*GC_TABLENAME_ADVPAIDRCM(30) VALUE 'GT_FINAL_ADVPAIDRCM',
*GC_STRUCTURE_ADVPAIDRCM(30) VALUE 'YGSTINWARD02_ST',
*GC_STRUCTURE_ADVPAIDRCM1(30) VALUE 'YGSTINWARD02_DIS',
*GC_TABLENAME_ADVADJRCM(30) VALUE 'GT_FINAL_ADVADJRCM',
*GC_STRUCTURE_ADVADJRCM(30) VALUE 'YGSTINWARD02_ST',
*GC_STRUCTURE_ADVADJRCM1(30) VALUE 'YGSTINWARD02_DIS',
*GC_TABLENAME_ITCREVERSAL(30) VALUE 'GT_FINAL_ITCREVERSAL',
*GC_STRUCTURE_ITCREVERSAL(30) VALUE 'YGSTINWARD03_ST',
*GC_STRUCTURE_ITCREVERSAL1(30) VALUE 'YGSTINWARD03_DIS',
*GC_TABLENAME_TDS(30) VALUE 'GT_FINAL_TDS',
*GC_STRUCTURE_TDS(30) VALUE 'YGSTINWARD04_ST',
*GC_STRUCTURE_TDS1(30) VALUE 'YGSTINWARD04_DIS',
*
*GC_AUTHORIZATION_ALL(2) VALUE '01',
*GC_AUTHORIZATION_REPORT(2) VALUE '02',
*GC_AUTHORIZATION_STAGING(2) VALUE '03',
*GC_AUTHORIZATION_DOWNLOAD(2) VALUE '04'.

DATA: gt_final_inward TYPE STANDARD TABLE OF ty_final_inward.
DATA: gt_final_inward1 TYPE STANDARD TABLE OF ty_final_inward1,
      gl_final_inward1 TYPE  ty_final_inward1,
*      GT_FINAL_INWARD_REV TYPE STANDARD TABLE OF TY_FINAL_INWARD,
**      GT_FINAL_INWARD_EY TYPE STANDARD TABLE OF TY_FINAL_INWARD_EY,  ""RK
**      GT_FINAL_INWARD_EY1 TYPE STANDARD TABLE OF TY_FINAL_INWARD_EY,
*      GT_FINAL_INWARD_EY2 TYPE STANDARD TABLE OF TY_FINAL_INWARD_EY2,  ""RK
      GS_FINAL_INWARD TYPE TY_FINAL_INWARD.
****      LS_FINAL_INWARD_EY TYPE TY_FINAL_INWARD_EY,
*      LS_FINAL_INWARD_EY TYPE TY_FINAL_INWARD_EY2,
**      LS_FINAL_INWARD_EY1 TYPE TY_FINAL_INWARD_EY,
*      LS_FINAL_INWARD_TEMP_EY TYPE TY_FINAL_INWARD_EY2,
*      LS_FINAL_INWARD_TEMP_EY_2 TYPE TY_FINAL_INWARD_EY2,
**      LS_FINAL_INWARD_TEMP_EY2 TYPE TY_FINAL_INWARD_EY,
**      GS_INWARD01 TYPE YGSTINWARD01,
**      GT_INWARD01 TYPE TABLE OF YGSTINWARD01,
**      GT_FINAL_ADVPAIDRCM TYPE STANDARD TABLE OF TY_FINAL_ADVPAIDRCM,
**      GS_FINAL_ADVPAIDRCM TYPE TY_FINAL_ADVPAIDRCM,
**      GT_FINAL_ADVADJRCM TYPE STANDARD TABLE OF TY_FINAL_ADVADJRCM,
**      GS_FINAL_ADVADJRCM TYPE TY_FINAL_ADVADJRCM,
*
**      GT_FINAL_ITCREVERSAL TYPE STANDARD TABLE OF TY_FINAL_ITCREVERSAL,
**      GS_FINAL_ITCREVERSAL TYPE TY_FINAL_ITCREVERSAL,
**      GT_FINAL_TDS TYPE STANDARD TABLE OF TY_FINAL_TDS,
**      GS_FINAL_TDS TYPE TY_FINAL_TDS,
*
*      GT_HEAD  TYPE STANDARD TABLE OF TY_HEAD,
*      GS_HEAD  TYPE TY_HEAD,
*      GT_FCAT  TYPE SLIS_T_FIELDCAT_ALV,
*      GS_FCAT  TYPE SLIS_FIELDCAT_ALV,
*      GS_LAYO  TYPE SLIS_LAYOUT_ALV,
*      GS_VARI  TYPE DISVARIANT.
*      GS_LOG   TYPE ZEXTRACTOR_LOG,
*      GT_LOG   TYPE TABLE OF ZEXTRACTOR_LOG.

*FIELD-SYMBOLS <FS_TABLE> TYPE STANDARD TABLE.

*RANGES: GR_BUDAT FOR BKPF-BUDAT.
*DATA: GV_GET_LIVE_DATA TYPE FLAG,
*      GV_GET_STAGING_DATA TYPE FLAG.
*
*TYPES : BEGIN OF TY_KTOSL,
*    KSCHL TYPE KSCHL,
*  END OF TY_KTOSL,
*
*  BEGIN OF TY_BSIS,
*    BUKRS TYPE BSIS-BUKRS,
*    HKONT TYPE BSIS-HKONT,
*    AUGDT TYPE BSIS-AUGDT,
*    AUGBL TYPE BSIS-AUGBL,
*    ZUONR TYPE BSIS-ZUONR,
*    GJAHR TYPE BSIS-GJAHR,
*    BELNR TYPE BSIS-BELNR,
*    BUZEI TYPE BSIS-BUZEI,
*    BUDAT TYPE BSIS-BUDAT,
*    BLDAT TYPE BSIS-BLDAT,
*  END OF TY_BSIS,
*  TTY_BSIS TYPE TABLE OF TY_BSIS,
*
*  BEGIN OF TY_1BBRANCH,
*    BUKRS  TYPE J_1BBRANCH-BUKRS,
*    BRANCH TYPE J_1BBRANCH-BRANCH,
*    NAME   TYPE J_1BBRANCH-NAME,
*    ADRNR  TYPE J_1BBRANCH-ADRNR,
*    GSTIN  TYPE J_1BBRANCH-GSTIN,
*    REGION  TYPE ADRC-REGION,
*  END OF TY_1BBRANCH,
*  TTY_1BBRANCH TYPE TABLE OF TY_1BBRANCH,
*
*  BEGIN OF TY_BKPF,
*    BUKRS TYPE BUKRS,
*    BELNR TYPE BELNR_D,
*    GJAHR TYPE GJAHR,
*    BLART TYPE BLART,
*    BLDAT TYPE BLDAT,
*    BUDAT TYPE BUDAT,
*    CPUDT TYPE CPUDT,
*    TCODE TYPE TCODE,
*    XBLNR TYPE XBLNR1,
*    USNAM TYPE USNAM,
*    STBLG TYPE STBLG,
*    STJAH TYPE STJAH,
** Inserted by Sheetal on 29 July 2017
*    XBLNR_ALT TYPE BKPF-XBLNR_ALT,
*    VATDATE TYPE VATDATE,
*    AWKEY TYPE BKPF-AWKEY,
*    STGRD TYPE BKPF-STGRD,
** End of insertion
** Inserted on 03082017
*    XREVERSAL TYPE BKPF-XREVERSAL,
*  END OF TY_BKPF,
*  TTY_BKPF TYPE TABLE OF TY_BKPF,
*
*  BEGIN OF TY_BSEG,
*    BUKRS TYPE BSEG-BUKRS,
*    BELNR TYPE BSEG-BELNR,
*    GJAHR TYPE BSEG-GJAHR,
*    BUZEI TYPE BSEG-BUZEI,
*    BUZID TYPE BSEG-BUZID,
*    AUGDT TYPE BSEG-AUGDT,
*    AUGBL TYPE BSEG-AUGBL,
*    BSCHL TYPE BSEG-BSCHL,
*    KOART TYPE BSEG-KOART,
*    UMSKZ TYPE BSEG-UMSKZ,
*    SHKZG TYPE BSEG-SHKZG,
*    GSBER TYPE BSEG-GSBER,
*    MWSKZ TYPE BSEG-MWSKZ,
*    DMBTR TYPE BSEG-DMBTR,
*    TXGRP TYPE BSEG-TXGRP,
*    KTOSL TYPE BSEG-KTOSL,
*    ZUONR TYPE BSEG-ZUONR,
*    KOSTL TYPE BSEG-KOSTL,
*    XINVE TYPE BSEG-XINVE,
*    SAKNR TYPE BSEG-SAKNR,
*    HKONT TYPE BSEG-HKONT,
*    LIFNR TYPE BSEG-LIFNR,
*    REBZG TYPE BSEG-REBZG,
*    REBZJ TYPE BSEG-REBZJ,
*    REBZZ TYPE BSEG-REBZZ,
*    REBZT TYPE BSEG-REBZT,
*    MATNR TYPE BSEG-MATNR,
*    WERKS TYPE BSEG-WERKS,
*    MENGE TYPE BSEG-MENGE,
*    MEINS TYPE BSEG-MEINS,
*    BUPLA TYPE BSEG-BUPLA,
*    EBELN TYPE BSEG-EBELN,
*    EBELP TYPE BSEG-EBELP,
*    PRCTR TYPE BSEG-PRCTR,
*    TAXPS TYPE BSEG-TAXPS,
*    GST_PART TYPE BSEG-GST_PART,
*    PLC_SUP TYPE BSEG-PLC_SUP,
*    HSN_SAC TYPE BSEG-HSN_SAC,
*  END OF TY_BSEG,
*  TTY_BSEG TYPE TABLE OF TY_BSEG,
*
*  BEGIN OF TY_BSET,
*    BUKRS TYPE BUKRS,
*    BELNR TYPE BELNR_D,
*    GJAHR TYPE GJAHR,
*    BUZEI TYPE BUZEI,
*    MWSKZ TYPE MWSKZ,
*    TXGRP TYPE TXGRP,
*    SHKZG TYPE SHKZG,
*    HWBAS TYPE HWBAS_BSES,
*    HWSTE TYPE HWSTE,
*    KTOSL TYPE KTOSL,
*    KSCHL TYPE KSCHL,
*    KBETR TYPE KBETR_TAX,
*    BUPLA TYPE BUPLA,
*    TAXPS TYPE TAX_POSNR,
*  END OF TY_BSET,
*  TTY_BSET TYPE TABLE OF TY_BSET,
*
*
*  BEGIN OF TY_EKKO,
*    EBELN TYPE EKKO-EBELN,
*    BSART TYPE EKKO-BSART,
*    LIFNR TYPE EKKO-LIFNR,
*    BEDAT TYPE EKKO-BEDAT,
*    WAERS TYPE EKKO-WAERS,
*  END OF TY_EKKO,
*  TTY_EKKO TYPE TABLE OF TY_EKKO,
*
*  BEGIN OF TY_EKPO,
*    EBELN TYPE EKPO-EBELN,
*    EBELP TYPE EKPO-EBELP,
*    TXZ01 TYPE EKPO-TXZ01,
*    MATNR TYPE EKPO-MATNR,
*    MENGE TYPE EKPO-MENGE,
*    MEINS TYPE EKPO-MEINS,
*    NETPR TYPE EKPO-NETPR,
*    NETWR TYPE EKPO-NETWR,
*    PSTYP TYPE EKPO-PSTYP,
*    KNTTP TYPE EKPO-KNTTP,
*  END OF TY_EKPO,
*  TTY_EKPO TYPE TABLE OF TY_EKPO,
*
*  BEGIN OF TY_LFA1,
*    LIFNR TYPE LFA1-LIFNR,
*    NAME1 TYPE LFA1-NAME1,
*    ADRNR TYPE LFA1-ADRNR,
*    REGIO TYPE LFA1-REGIO,
*    LAND1 TYPE LFA1-LAND1,
*    STCD3 TYPE LFA1-STCD3,
*    FITYP TYPE LFA1-FITYP,
*  END OF TY_LFA1,
*  TTY_LFA1 TYPE TABLE OF TY_LFA1,
*
*  BEGIN OF TY_ADRC,
*    ADDRNUMBER TYPE ADRC-ADDRNUMBER,
*    NAME1      TYPE ADRC-NAME1,
*    NAME2      TYPE ADRC-NAME2,
*    CITY1      TYPE ADRC-CITY1,
*    POST_CODE1 TYPE ADRC-POST_CODE1,
*    STREET     TYPE ADRC-STREET,
*    STR_SUPPL1 TYPE ADRC-STR_SUPPL1,
*    STR_SUPPL2 TYPE ADRC-STR_SUPPL2,
*    STR_SUPPL3 TYPE ADRC-STR_SUPPL3,
*    REGION     TYPE ADRC-REGION,
*  END OF TY_ADRC,
*  TTY_ADRC TYPE TABLE OF TY_ADRC,
*
*  BEGIN OF TY_KNA1,
*    KUNNR TYPE KUNNR,
*    NAME1 TYPE NAME1_GP,
*    ADRNR TYPE ADRNR,REGIO TYPE REGIO,
*    STCD3 TYPE STCD3,
*  END OF TY_KNA1,
*  TTY_KNA1 TYPE TABLE OF TY_KNA1,
*
*  BEGIN OF TY_MARA,
*    MATNR TYPE MATNR,
*    MTART TYPE MTART,
*    MATKL TYPE MATKL,
*  END OF TY_MARA,
*  TTY_MARA TYPE TABLE OF TY_MARA,
*
*  BEGIN OF TY_MAKT,
*    MATNR TYPE MATNR,
*    MAKTX TYPE MAKTX,
*  END OF TY_MAKT,
*  TTY_MAKT TYPE TABLE OF TY_MAKT,
*
**  BEGIN OF TY_ZPARAM,
**    PARAM1 TYPE ZPARAM-PARAM1,
**    VKORG TYPE ZPARAM-VKORG,
**  END OF TY_ZPARAM,
**  TTY_ZPARAM TYPE TABLE OF TY_ZPARAM,
*
*  BEGIN OF TY_MARC,
*    MATNR TYPE MATNR,
*    WERKS TYPE WERKS_D,
*    STEUC TYPE STEUC,
*  END OF TY_MARC,
*  TTY_MARC TYPE TABLE OF TY_MARC,
*  BEGIN OF TY_DOCCOMPRESS,
*    BUKRS TYPE BUKRS,
*    BELNR TYPE BKPF-BELNR,
*    GJAHR TYPE BKPF-GJAHR,
*  END OF TY_DOCCOMPRESS,
*  BEGIN OF TY_POCOMPRESS,
*    EBELN TYPE EKPO-EBELN,
*    EBELP TYPE EKPO-EBELP,
*  END OF TY_POCOMPRESS,
*  BEGIN OF TY_VENCOMPRESS,
*    LIFNR TYPE LFA1-LIFNR,
*  END OF TY_VENCOMPRESS,
*  BEGIN OF TY_MLAN,
*    MATNR TYPE MATNR,
*    ALAND TYPE ALAND,
*    TAXIM TYPE TAXIM1,
*  END OF TY_MLAN,
*  BEGIN OF TY_MOVEND,
*    LIFNR TYPE LIFNR,
*    VEN_CLASS TYPE J_1IGTAKLD,
*  END OF TY_MOVEND,
*  BEGIN OF TY_MATNRCOMPRESS,
*    MATNR TYPE MATNR,
*  END OF TY_MATNRCOMPRESS,
*
*  BEGIN OF TY_BSET_SUMMARY,
*    BUKRS TYPE BUKRS,
*    BELNR TYPE BELNR_D,
*    GJAHR TYPE GJAHR,
*    TAXPS TYPE TAXPS,
*  END OF TY_BSET_SUMMARY,
*
*  BEGIN OF TY_T003,
*    BLART TYPE BLART,
*    KOARS TYPE KOARS_003,
*  END OF TY_T003,
*
*  BEGIN OF TY_RSEGCOMPRESS,
*    BELNR TYPE BELNR_D,
*    GJAHR TYPE GJAHR,
*  END OF TY_RSEGCOMPRESS,
*
*  BEGIN OF TY_T604N,
*    STEUC TYPE STEUC,
*    TEXT1 TYPE BEZEI60,
*  END OF TY_T604N,
*
*  BEGIN OF TY_J_1IG_GST_JV,
*    REF_DOC TYPE J_1IG_GST_JV-REF_DOC,
*    BUKRS TYPE BUKRS,
*    GJAHR TYPE GJAHR,
*    BUZEI TYPE BUZEI,
*  END OF TY_J_1IG_GST_JV,
*
*  BEGIN OF TY_SKAT,
*    SAKNR TYPE SAKNR,
*    KTOPL TYPE KTOPL,
*
*    TXT50 TYPE TXT50,
*    END OF TY_SKAT,
*
*  BEGIN OF TY_BSEC,
*    BUKRS TYPE BUKRS,
*    BELNR TYPE BELNR_D,
*    GJAHR TYPE GJAHR,
*    NAME1 TYPE BSEC-NAME1,
*    STCD3 TYPE BSEC-STCD3,
*  END OF TY_BSEC.
*
*DATA : BATCH TYPE CHAR25.
*
*DATA: LS_BSIS TYPE TY_BSIS,
*      LT_BSIS TYPE TABLE OF TY_BSIS,
*      LS_1BBRANCH TYPE TY_1BBRANCH,
*      LT_1BBRANCH TYPE TABLE OF TY_1BBRANCH WITH HEADER LINE,
*      LS_T030K TYPE J_1IT030K,
*      LT_T030K TYPE TABLE OF J_1IT030K,
*      LS_BKPF TYPE TY_BKPF,
*      LT_BKPF TYPE TABLE OF TY_BKPF,
*      LT_BKPF_CAN TYPE TABLE OF TY_BKPF,
*      LT_BKPF_M TYPE TABLE OF TY_BKPF,
*      LS_BKPF_M TYPE TY_BKPF,
*      LT_BKPF_CAN1 TYPE TABLE OF TY_BKPF,
*      LT_BKPF_CAN_N TYPE TABLE OF TY_BKPF,
*      LS_BKPF_REF TYPE TY_BKPF,
*      LS_BKPF_CAN TYPE TY_BKPF,
*      LS_BKPF_CAN1 TYPE TY_BKPF,
*      LS_BKPF_CAN_N TYPE TY_BKPF,
*      LT_BKPF_REF TYPE TABLE OF TY_BKPF,
*      LT_BSEG TYPE TABLE OF TY_BSEG,
*      LT_BSEG_TMP TYPE TABLE OF TY_BSEG,
*      LS_BSEG_TMP TYPE TY_BSEG,
*      LS_BSEG TYPE TY_BSEG,
*      LS_BSET TYPE TY_BSET,
*      LT_BSET TYPE TABLE OF TY_BSET,
*      LT_BSEG_K TYPE TABLE OF TY_BSEG,
*      LS_BSEG_K TYPE TY_BSEG,
*      LT_BSEG_T TYPE TABLE OF TY_BSEG,
*      LS_BSEG_T TYPE TY_BSEG,
*      LT_BSEG_W TYPE TABLE OF TY_BSEG,
*      LS_BSEG_W TYPE TY_BSEG,
*      LS_MARA TYPE TY_MARA,
*      LT_MARA TYPE SORTED TABLE OF TY_MARA WITH UNIQUE KEY MATNR,
*      LS_MAKT TYPE TY_MAKT,
*      LT_MAKT TYPE SORTED TABLE OF TY_MAKT WITH UNIQUE KEY MATNR,
**      LS_ZPARAM TYPE TY_ZPARAM,
**      LT_ZPARAM TYPE TABLE OF TY_ZPARAM,
*      LS_EKKO TYPE TY_EKKO,
*      LT_EKKO TYPE SORTED TABLE OF TY_EKKO WITH UNIQUE KEY EBELN,
*      LS_EKPO TYPE TY_EKPO,
*      LT_EKPO TYPE SORTED TABLE OF TY_EKPO WITH UNIQUE KEY EBELN EBELP,
*      LS_LFA1 TYPE TY_LFA1,
*      LT_LFA1 TYPE SORTED TABLE OF TY_LFA1 WITH UNIQUE KEY LIFNR,
*      LS_T001 TYPE T001,
*      LS_T003 TYPE TY_T003,
*      LT_T003 TYPE TABLE OF TY_T003,
**      LS_TRANSKEY TYPE ZGSTNTTRANSKEY,
**      LT_TRANSKEY TYPE TABLE OF ZGSTNTTRANSKEY,
*      LT_TRANSKEY1 TYPE STANDARD TABLE OF TY_KTOSL,
*      LS_TRANSKEY1 TYPE TY_KTOSL,
*      LS_POCOMPRESS TYPE TY_POCOMPRESS,
*      LT_POCOMPRESS TYPE TABLE OF TY_POCOMPRESS,
*      LS_VENCOMPRESS TYPE TY_VENCOMPRESS,
*      LT_VENCOMPRESS TYPE TABLE OF TY_VENCOMPRESS,
*      LS_MATNRCOMPRESS TYPE TY_MATNRCOMPRESS,
*      LT_MATNRCOMPRESS TYPE TABLE OF TY_MATNRCOMPRESS,
*      LS_DOCCOMPRESS TYPE TY_DOCCOMPRESS,
*      LT_DOCCOMPRESS TYPE TABLE OF TY_DOCCOMPRESS,
*      LS_BSET_SUMMARY TYPE TY_BSET_SUMMARY,
*      LT_BSET_SUMMARY TYPE TABLE OF TY_BSET_SUMMARY,
*      LT_BSET_SUMMARY1 TYPE TABLE OF TY_BSET_SUMMARY,
*      LS_RSEGCOMPRESS TYPE TY_RSEGCOMPRESS,
*      LT_RSEGCOMPRESS TYPE TABLE OF TY_RSEGCOMPRESS,
*      LS_BSEC TYPE TY_BSEC,
*      LT_BSEC TYPE TABLE OF TY_BSEC,
*      LV_STRUCTURENAME(30),
*      LS_MLAN TYPE TY_MLAN,
*      LT_MLAN TYPE TABLE OF TY_MLAN,
*      LS_MOVEND TYPE TY_MOVEND,
*      LT_MOVEND TYPE TABLE OF TY_MOVEND,
*      LS_ZGSTNDOCTYPE TYPE ZDMDOCTYPE,
*      LT_ZGSTNDOCTYPE TYPE TABLE OF ZDMDOCTYPE,
**      LT_ZGSTNSTATECODE TYPE TABLE OF ZGSTNSTATECODE,
**      LS_ZGSTNSTATECODE TYPE ZGSTNSTATECODE,
*      LS_DOCTYPE TYPE ZDMDOCTYPE,
*      LT_DOCTYPE TYPE TABLE OF ZDMDOCTYPE,
**      LS_SUPPLYTYPE TYPE ZGSTNSUPPLYTYPE,
**      LT_SUPPLYTYPE TYPE TABLE OF ZGSTNSUPPLYTYPE,
**      LS_STATECODE TYPE ZGSTNSTATECODE,
**      LT_STATECODE TYPE TABLE OF ZGSTNSTATECODE,
*      LT_T604N TYPE TABLE OF TY_T604N,
*      LS_T604N TYPE TY_T604N,
*      LT_J_1IG_GST_JV TYPE TABLE OF TY_J_1IG_GST_JV,
*      LS_J_1IG_GST_JV TYPE TY_J_1IG_GST_JV,
*      LS_FINAL_INWARD TYPE TY_FINAL_INWARD,
*      LS_FINAL_IN TYPE TY_FINAL_INWARD,
*      LT_SKAT TYPE TABLE OF TY_SKAT,
**      LT_SKAT2 TYPE TABLE OF TY_SKAT,
*      LS_SKAT2 TYPE TY_SKAT,
*      LS_SKAT TYPE TY_SKAT,
*""""""""""""""""""""Supply type"""""""""""""""""""""""
*      LV_TAXIM TYPE TAXIM1,
*      LV_VEN_CLASS TYPE J_1IGTAKLD,
*      LV_BLART TYPE BLART,
*      LV_MWSKZ TYPE MWSKZ,
*      LV_KTOSL TYPE KTOSL,
*      LV_KSCHL TYPE KSCHL,
*      LV_LAND1 TYPE CHAR03,
*      LV_BLDAT TYPE BLDAT,
****      lv_batch TYPE char25,
*      LV_SUCCESS_FLAG,
*      LV_HSN_SAC TYPE BSEG-HSN_SAC,
*      LV_MATNR TYPE MATNR,
*      LV_CHAR5 TYPE CHAR5,
*      LV_SHKZG TYPE SHKZG,
*      LV_FITYP TYPE LFA1-FITYP.

*DATA LV_TAX_TYPE TYPE KSCHL.
*RANGES: LR_KTOSL FOR J_1IT030K-KTOSL,
*        LR_BLART FOR BKPF-BLART,
*        LR_KSCHL1 FOR BSET-KSCHL.
*FIELD-SYMBOLS <FS_FINAL_INWARD> TYPE TY_FINAL_INWARD.

*DATA : LT_UOM TYPE STANDARD TABLE OF ZGST_UOM,
*        LS_UOM TYPE ZGST_UOM,
*
*        LT_REASON TYPE STANDARD TABLE OF ZGST_REASON,
*       LS_REASON TYPE ZGST_REASON.

DATA: lv_batch TYPE batch.

DATA: lv_sub_flag TYPE c.
***Variables************************************************************
DATA : g_var_response      TYPE char1.
**.... End of insertion of code by Mayur M on 21.01.2020 #++LRDK964118:LRDK964119 ....**
