*&---------------------------------------------------------------------*
*& Include          ZDM_GLOBAL_GENERATOR_TOP
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*Title         : ZDM_SALES_GENERATOR                                *
* Author        :                                                    *
* Company       : cygnet                                   *
* Creation Date : 24.03.2020                                           *
* Transaction   : ZDM_SALES                                          *
* Request ID    :  IHDK905695                                           *
* Ticket No.    : NA                                                   *
* Functional C. : Nikunj Goswami                                          *
* Package       : ZCYGNET                                           *
* Description   : CYGNET Utility                 *
* NOTE : ASP extractor - DM reporting requirment
*----------------------------------------------------------------------*

TABLES: vbrk,j_1it030k,bsad, bsid, bkpf.
TYPE-POOLS slis.
DATA : it_fcat TYPE slis_t_fieldcat_alv . "field catalog table
DATA : wa_fcat       LIKE LINE OF it_fcat , "field catalog work area
       gs_str_layout TYPE slis_layout_alv.

DATA : it_listheader TYPE slis_t_listheader,
       wa_listheader TYPE slis_listheader.
*TYPES: BEGIN OF ty_vbrl,
*         vbeln    TYPE vbrl-vbeln,
*         posnr    TYPE vbrl-posnr,
*         vbeln_vf TYPE vbrl-vbeln_vf,
*         netwr    TYPE vbrl-netwr,
*         mwsbp    TYPE vbrl-mwsbp,
*       END OF ty_vbrl.
*TYPES: BEGIN OF ty_vbrl1,
*         vbeln TYPE vbrl-vbeln,
**               POSNR TYPE VBRL-POSNR,
**               VBELN_VF TYPE VBRL-VBELN_VF,
*         netwr TYPE vbrl-netwr,
*         mwsbp TYPE vbrl-mwsbp,
*       END OF ty_vbrl1.
*DATA: l_tab_vbrl TYPE STANDARD TABLE OF ty_vbrl.
*DATA: l_tab_vbrl2 TYPE STANDARD TABLE OF ty_vbrl.
*DATA: l_str_vbrl TYPE ty_vbrl.
*DATA: l_tab_vbrl1 TYPE STANDARD TABLE OF ty_vbrl1.
*DATA: l_str_vbrl1 TYPE ty_vbrl1.


*TYPES: BEGIN OF ty_final_outward_ey1.
**        TYPES:fi_doc type char10.
*TYPES:fi_doc TYPE char12.
*TYPES:hsn TYPE char10.
**        TYPES:Rate type char10.
*TYPES:matnr TYPE matnr.
*TYPES:unitofmeasurement1 TYPE char3.

*TYPES:END OF ty_final_outward_ey1.

TYPES: BEGIN OF ty_final_outward.
    INCLUDE STRUCTURE zdm_global.
TYPES: END OF ty_final_outward,
tty_final_main TYPE TABLE OF ty_final_outward.
TYPES: BEGIN OF ty_vbrk ,
         vbeln   TYPE vbrk-vbeln,     "Billing Document ,vbrk
         gjahr   TYPE vbrk-gjahr,
         posnr   TYPE vbrp-posnr,     "Billing item
         knumv   TYPE vbrk-knumv,     "Number of the document condition vbrp
         fkart   TYPE vbrk-fkart,     "Billing Type ,vbrk
         fktyp   TYPE vbrk-fktyp,     "Billing category VBRK
         vbtyp   TYPE vbrk-vbtyp,     "SD document category  vbrk
         waerk   TYPE vbrk-waerk,     "SD document Currency  vbrk
         vkorg   TYPE vbrk-vkorg,     "Sales Organization vbrk
         fkdat   TYPE vbrk-fkdat,     "Billing date for billing index and printout  vbrk
         kurrf   TYPE vbrk-kurrf,     "Exchange rate for FI postings  VBRK
         bupla   TYPE vbrk-bupla,     "Business Place vbrk
         bukrs   TYPE vbrk-bukrs,     "Company Code   vbrk
         regio   TYPE vbrk-regio,     "Region (State, Province, County) vbrk
         netwr   TYPE vbrk-netwr,     "Net Value in Document Currency  vbrk
         kunrg   TYPE vbrk-kunrg,     "Payer  vbrk
         kunag   TYPE vbrk-kunag,     "Sold-to party  vbrk
         sfakn   TYPE vbrk-sfakn,     "Cancelled billing document number    vbrk
         xblnr   TYPE vbrk-xblnr,     "Reference Document Number  vbrk
         zuonr   TYPE vbrk-zuonr,     "Assignment number  vbrk
         mwsbk   TYPE vbrk-mwsbk,     "Tax amount in document currency vbrk
         fksto   TYPE vbrk-fksto,     "Billing document is cancelled vbrk
         rfbsk   TYPE vbrk-rfbsk,
         aubel   TYPE vbrp-aubel,     "Sales Document  vbrp
         fkimg   TYPE vbrp-fkimg,     "Actual Invoiced Quantity  vbrp
         i_netwr TYPE vbrp-netwr,     "Net value of the billing item in document currency vbrp
         matnr   TYPE vbrp-matnr,     "Article Number   vbrp
         arktx   TYPE vbrp-arktx,
         werks   TYPE vbrp-werks,      "Plant vbrp
         vrkme   TYPE vbrp-vrkme,
       END OF ty_vbrk,
       BEGIN OF ty_konv,
         knumv TYPE prcd_elements-knumv,
         kposn TYPE prcd_elements-kposn,
         kschl TYPE prcd_elements-kschl,
         kawrt TYPE prcd_elements-kawrt,
         kbetr TYPE prcd_elements-kbetr,
         kwert TYPE prcd_elements-kwert,
       END OF ty_konv,
       BEGIN OF ty_t001w1,
         werks TYPE t001w-werks,
         name1 TYPE t001w-name1,
         lifnr TYPE t001w-lifnr,
         pstlz TYPE t001w-pstlz,
         ort01 TYPE t001w-ort01,
         regio TYPE t001w-regio,
       END OF ty_t001w1,
       BEGIN OF ty_kna11,
         kunnr TYPE kna1-kunnr,
         land1 TYPE kna1-land1,
         stcd3 TYPE kna1-stcd3,
       END OF ty_kna11,
       BEGIN OF ty_lfa1,
         lifnr TYPE lfa1-lifnr,
         land1 TYPE lfa1-land1,
         stcd3 TYPE lfa1-stcd3,
       END OF ty_lfa1,
       BEGIN OF ty_vbpa,
         vbeln TYPE vbpa-vbeln,
         posnr TYPE vbpa-posnr,
         parvw TYPE vbpa-parvw,
         kunnr TYPE vbpa-kunnr,
         adrnr TYPE vbpa-adrnr,
         land1 TYPE vbpa-land1,
       END OF ty_vbpa,
       types,
       BEGIN OF ty_bkpf_fi,
         bukrs TYPE bkpf-bukrs,
         belnr TYPE bkpf-belnr,
         gjahr TYPE bkpf-gjahr,
         awkey TYPE bkpf-awkey,
         awtyp TYPE bkpf-awtyp,
         xblnr TYPE bkpf-xblnr,
         budat TYPE bkpf-budat,
         blart TYPE bkpf-blart,
         bldat TYPE bkpf-bldat,
         waers TYPE bkpf-waers,
         kursf TYPE bkpf-kursf,
       END OF ty_bkpf_fi,
       BEGIN OF ity_bkpf,
         bukrs TYPE bkpf-bukrs,
         belnr TYPE bkpf-belnr,
         gjahr TYPE bkpf-gjahr,
         awkey TYPE bkpf-awkey,
       END OF ity_bkpf,
       BEGIN OF ity_awkey,
         vbeln TYPE vbrk-vbeln,
         awkey TYPE bkpf-awkey,
       END OF ity_awkey,

       BEGIN OF ty_bkpf1,
         bukrs TYPE bkpf-bukrs,
         belnr TYPE bkpf-belnr,
         gjahr TYPE bkpf-gjahr,
         xblnr TYPE bkpf-xblnr,
       END OF ty_bkpf1,
       BEGIN OF ty_bset1,
         bukrs TYPE bset-bukrs,
         belnr TYPE bset-belnr,
         gjahr TYPE bset-gjahr,
*        xblnr TYPE bkpf-xblnr,
       END OF ty_bset1.
         TYPES:
    BEGIN OF ty_out_invoice,
      location_gstin               TYPE char50,
      location_legal_name          TYPE char50,
      document_purpose             TYPE char50,
      supply_type                  TYPE char50,
      sub_supply_type              TYPE char50,
      sub_supply_description       TYPE char50,
      document_type                TYPE char50,
      document_no                  TYPE char50,
      series_code                  TYPE char50,
      document_date                TYPE char50,
      reference_doc_type           TYPE char50,
      reference_doc_no             TYPE char50,
      reference_doc_date           TYPE char50,
      transaction_type             TYPE char50,
      pos                          TYPE char50,
      bill_from_gstin              TYPE char50,
      bill_from_oth_party_name     TYPE char50,
      bill_from_address1           TYPE char50,
      bill_from_address2           TYPE char50,
      bill_from_city               TYPE char50,
      bill_from_state              TYPE char50,
      bill_from_post_code          TYPE char50,
      dispatch_from_gstin          TYPE char50,
      dispatch_from_oth_party_name TYPE char50,
      dispatch_from_address1       TYPE char50,
      dispatch_from_address2       TYPE char50,
      dispatch_from_city           TYPE char50,
      dispatch_from_state          TYPE char50,
      dispatch_from_post_code      TYPE char50,
      ctin                         TYPE char50,
      email                        TYPE char50,
      mobile                       TYPE char50,
      bill_to_gstin                TYPE char50,
      bill_to_name                 TYPE char50,
      bill_to_address1             TYPE char50,
      bill_to_address2             TYPE char50,
      bill_to_state                TYPE char50,
      bill_to_city                 TYPE char50,
      bill_to_post_code            TYPE char50,
      ship_to_gstin                TYPE char50,
      ship_to_name                 TYPE char50,
      ship_to_address1             TYPE char50,
      ship_to_address2             TYPE char50,
      ship_to_state                TYPE char50,
      ship_to_city                 TYPE char50,
      ship_to_post_code            TYPE char50,
      document_value               TYPE char50,
      outstanding_amount           TYPE char50,
      reference_no                 TYPE char50,
      diff_percentage              TYPE char50,
      rev_charges                  TYPE char50,
      gstin_of_ecomm               TYPE char50,
      ship_bill_no                 TYPE char50,
      ship_bill_date               TYPE char50,
      port_code                    TYPE char50,
      trans_id                     TYPE char50,
      trans_name                   TYPE char50,
      trans_date                   TYPE char50,
      trans_time                   TYPE char50,
      distance                     TYPE char50,
      trans_mode                   TYPE char50,
      trans_doc_no                 TYPE char50,
      trans_doc_date               TYPE char50,
      vehical_no                   TYPE char50,
      vehical_type                 TYPE char50,
      orig_gstin                   TYPE char50,
      orig_doc_no                  TYPE char50,
      orig_doc_date                TYPE char50,
      product_name                 TYPE char50,
      description                  TYPE char50,
      hsn                          TYPE char50,
      quantity                     TYPE char50,
      uom                          TYPE char50,
      tax_value                    TYPE char50,
      discount_amount              TYPE char50,
      igst_rate                    TYPE char50,
      igst_amount                  TYPE char50,
      cgst_rate                    TYPE char50,
      cgst_amount                  TYPE char50,
      sgst_rate                    TYPE char50,
      sgst_amount                  TYPE char50,
      cess_rate                    TYPE char50,
      cess_amt                     TYPE char50,
      cess_non_adval_rate          TYPE char50,
      cess_non_adval_amt           TYPE char50,
      other_charges                TYPE char50,
      elig_itc                     TYPE char50,
      intr_itc_amt                 TYPE char50,
      cent_itc_amt                 TYPE char50,
      ut_itc_amt                   TYPE char50,
      cess_itc_amt                 TYPE char50,
      custom1                      TYPE char50,
      custom2                      TYPE char50,
      custom3                      TYPE char50,
      custom4                      TYPE char50,
      custom5                      TYPE char50,
      custom6                      TYPE char50,
      custom7                      TYPE char50,
      custom8                      TYPE char50,
      custom9                      TYPE char50,
      custom10                     TYPE char50,
      werks                        TYPE werks_d,
      bukrs                        TYPE bukrs,
      doc_status                   TYPE char40,
    END OF ty_out_invoice,

       BEGIN OF ty_t001w,
         werks      TYPE t001w-werks,
         name1      TYPE t001w-name1,
         pstlz      TYPE t001w-pstlz,
         ort01      TYPE t001w-ort01,
         j_1bbranch TYPE t001w-j_1bbranch,
         regio      TYPE t001w-regio,
       END OF ty_t001w,
       BEGIN OF ty_kna1,
         kunnr TYPE kna1-kunnr,
         name1 TYPE kna1-name1,
         ort01 TYPE kna1-ort01,
         pstlz TYPE kna1-pstlz,
         regio TYPE kna1-regio,
         stcd3 TYPE kna1-stcd3,
         land1 TYPE kna1-land1,
       END OF ty_kna1,

       BEGIN OF ty_kna1_fi,
         kunnr TYPE kna1-kunnr,        " Customer Number
         land1 TYPE kna1-land1,
         name1 TYPE kna1-name1,        " Name 1
         regio TYPE regio,
         stras TYPE stras_gp,          " House number and street
         adrnr TYPE adrnr,             " Address
         stcd3 TYPE stcd3,
         ort01 TYPE ort01,
         pstlz TYPE pstlz,
       END OF ty_kna1_fi,

       BEGIN OF ty_lfa1_dfi,
          lifnr TYPE lfa1-lifnr,
          land1 TYPE lfa1-land1,
         name1  TYPE lfa1-name1,
         regio TYPE lfa1-regio,
           ort01 TYPE ort01,
         stcd3 TYPE stcd3,
         END OF ty_lfa1_dfi,

       BEGIN OF ty_j_1bbranch,
         bukrs  TYPE j_1bbranch-bukrs,
         branch TYPE j_1bbranch-branch,
         name   TYPE j_1bbranch-name,
         gstin  TYPE j_1bbranch-gstin,
       END OF ty_j_1bbranch,
       BEGIN OF ty_vbfa,
         vbelv   TYPE vbfa-vbelv,
         posnv   TYPE vbfa-posnv,
         vbeln   TYPE vbfa-vbeln,
         vbtyp_n TYPE vbfa-vbtyp_n,
         vbtyp_v TYPE vbfa-vbtyp_v,
       END OF ty_vbfa,
       BEGIN OF ty_vbrk_refdate,
         vbeln TYPE vbrk-vbeln,
         fkdat TYPE vbrk-fkdat,
       END OF ty_vbrk_refdate.


TYPES : BEGIN OF ty_bseg,
          bukrs    TYPE bukrs,
          belnr    TYPE belnr_d,
          vbeln    TYPE vbeln,
          gjahr    TYPE gjahr,
          buzei    TYPE buzei,
          txgrp    TYPE txgrp,
          buzid    TYPE buzid,
          bupla    TYPE bseg-bupla,
          hsn_sac  TYPE bseg-hsn_sac,
          plc_sup  TYPE bseg-plc_sup,
          gst_part TYPE bseg-gst_part,
          matnr    TYPE bseg-matnr,
          werks    TYPE bseg-werks,
          wrbtr    TYPE bseg-wrbtr,
          kunnr    TYPE bseg-kunnr,
          menge    TYPE bseg-menge,
          hkont    TYPE bseg-hkont,
          gsber    TYPE bseg-gsber,
          lifnr    TYPE bseg-lifnr,
          sgtxt    TYPE bseg-sgtxt,
          KIDNO    TYPE BSEG-KIDNO,
        END OF ty_bseg,

BEGIN OF ty_temp,
         sgtxt type bkpf-xblnr,
         gjahr TYPE bkpf-gjahr,
  END OF ty_temp,
        BEGIN OF ty_bset,
          bukrs TYPE bukrs,
          belnr TYPE belnr_d,
          gjahr TYPE gjahr,
          buzei TYPE buzei,
          txgrp TYPE txgrp,
          shkzg TYPE shkzg,
          fwbas TYPE fwbas_bses,
          fwste TYPE fwste,
          kschl TYPE kschl,
          kbetr TYPE kbetr_tax,
          bupla TYPE bupla,
        END OF ty_bset,

        BEGIN OF ty_marc,
          matnr TYPE matnr,
          werks TYPE werks_d,
          steuc TYPE steuc,
        END OF ty_marc,

        BEGIN OF ty_gs_errinv1,
          errstr TYPE string,
        END OF ty_gs_errinv1.
DATA: l_tab_doctype         TYPE TABLE OF zdmdoctype,
      l_tab_doctype1        TYPE TABLE OF zdmdoctype,
      l_str_doctype         TYPE zdmdoctype,
      l_tab_bus_id          TYPE TABLE OF zei_bus_id,
      l_str_bus_id          TYPE zei_bus_id,
      l_tab_bus_unit_id     TYPE TABLE OF zei_bus_unit_id,
      l_str_bus_unit_id     TYPE zei_bus_unit_id,
      l_str_cust_data       TYPE zei_cust_data,
      l_tab_zei_uom_maping  TYPE TABLE OF zei_uom_maping,
      l_str_zei_uom_maping  TYPE zei_uom_maping,
      l_tab_zgst_state_code TYPE TABLE OF zei_state_code,
      l_str_zgst_state_code TYPE zei_state_code,
      l_str_kna1_tt         TYPE ty_kna1,
      l_tab_vbrk            TYPE STANDARD TABLE OF ty_vbrk,
      l_tab_konv            TYPE STANDARD TABLE OF ty_konv,
      l_str_konv            TYPE ty_konv,
      l_tab_vbpa            TYPE STANDARD TABLE OF ty_vbpa,
      l_tab_vbpa_tt         TYPE STANDARD TABLE OF ty_vbpa,

      l_tab_cust_gstin      TYPE STANDARD TABLE OF ty_kna11,
      l_tab_ven_gstin       TYPE STANDARD TABLE OF ty_lfa1,
      l_tab_t001w1          TYPE STANDARD TABLE OF ty_t001w1,
      l_tab_bkpf_fi         TYPE STANDARD TABLE OF ty_bkpf_fi,
      l_str_bkpf_fi         TYPE ty_bkpf_fi,
      l_tab_bkpf1           TYPE STANDARD TABLE OF  ty_bkpf1,
      l_tab_bset1           TYPE STANDARD TABLE OF ty_bset1,
      l_str_bkpf1           TYPE ty_bkpf1,
      l_tab_bkpf_dfi        TYPE STANDARD TABLE OF ty_bkpf_fi,
      l_tab_bkpf_dfi_sgtxt  TYPE STANDARD TABLE OF ty_bkpf_fi,
        l_tab_bkpf_dfi_kidno  TYPE STANDARD TABLE OF ty_bkpf_fi,
      l_tab_bseg_dfi_kunnr  TYPE STANDARD TABLE OF ty_bseg,
       l_tab_bseg_dfi_lifnr  TYPE STANDARD TABLE OF ty_bseg,
      l_tab_bseg_dfi_hsn    TYPE STANDARD TABLE OF ty_bseg,
      l_tab_bseg_dfi_sgtxt  TYPE STANDARD TABLE OF ty_bseg,
         l_tab_bseg_dfi_sgtxt1  TYPE STANDARD TABLE OF ty_bseg,
        l_tab_bseg_dfi_kidno  TYPE STANDARD TABLE OF ty_bseg,
      l_tab_temp TYPE STANDARD TABLE OF ty_temp,
      l_tab_temp1 TYPE STANDARD TABLE OF ty_temp,
      l_str_bkpf_dfi        TYPE ty_bkpf_fi,
      l_tab_bseg            TYPE STANDARD TABLE OF ty_bseg,
      l_tab_bseg_dfi        TYPE STANDARD TABLE OF ty_bseg,
      l_str_bseg_dfi_hsn    TYPE  ty_bseg,
      l_tab_t001w           TYPE STANDARD TABLE OF ty_t001w,
      l_tab_kna1            TYPE STANDARD TABLE OF ty_kna1,
      l_str_kna1            TYPE ty_kna1,
      l_str_bkpf_dfi_sgtxt  TYPE ty_bkpf_fi,
      l_str_bkpf_dfi_kidno  TYPE ty_bkpf_fi,
      l_tab_final           TYPE STANDARD TABLE OF zdm_global,
* l_tab_final           TYPE STANDARD TABLE OF ty_out_invoice,
      l_str_final           TYPE zdm_global,
      ls_final TYPE ty_out_invoice,
      l_str_doctype1        TYPE zdmdoctype,
      l_str_bset1           TYPE ty_bset1,

      l_tab_j_1bbranch      TYPE STANDARD TABLE OF ty_j_1bbranch,
      l_tab_bkpf            TYPE TABLE OF ity_bkpf,
      l_tab_awkey           TYPE TABLE OF ity_awkey,
      l_str_awkey           TYPE ity_awkey,
      l_str_temp            TYPE ty_temp,
        l_str_temp1           TYPE ty_temp,
      l_str_vbpa            TYPE ty_vbpa,
      l_str_vbpa_tt         TYPE ty_vbpa,
      l_str_t001w           TYPE ty_t001w,
      l_str_j_1bbranch      TYPE ty_j_1bbranch,
      l_str_cust_gstin      TYPE ty_kna11,
      l_str_t001w1          TYPE ty_t001w1,
      l_str_ven_gstin       TYPE ty_lfa1,
      l_tab_kna1_fi         TYPE STANDARD TABLE OF ty_kna1_fi,
      l_tab_kna1_dfi        TYPE STANDARD TABLE OF ty_kna1_fi,
     l_tab_lfa1_dfi         TYPE STANDARD TABLE OF ty_lfa1_dfi,
      l_tab_kna1_tt         TYPE STANDARD TABLE OF ty_kna1,
      l_str_bseg            TYPE ty_bseg,
      l_str_bseg_dfi_sgtxt  TYPE ty_bseg,
          l_str_bseg_dfi_sgtxt1  TYPE ty_bseg,
       l_str_bseg_dfi_kidno  TYPE ty_bseg,
      l_str_bset_dfi        TYPE ty_bset,
      l_str_bseg_dfi        TYPE ty_bseg,
      l_str_bseg_dfi_kunnr  TYPE ty_bseg,
         l_str_bseg_dfi_lifnr  TYPE ty_bseg,
      l_tab_bset            TYPE STANDARD TABLE OF ty_bset,
      l_tab_bset_dfi        TYPE STANDARD TABLE OF ty_bset,
      l_str_bset            TYPE ty_bset,
      l_tab_marc            TYPE STANDARD TABLE OF ty_marc,
      l_str_marc            TYPE ty_marc,
      l_str_vbrk            TYPE ty_vbrk,
      l_tab_bseg_temp       TYPE STANDARD TABLE OF ty_bseg,
      l_str_bseg_temp       TYPE ty_bseg,

      l_str_kna1_fi         TYPE ty_kna1_fi,
      l_str_kna1_dfi        TYPE ty_kna1_fi,
      l_str_lfa1_dfi        TYPE ty_lfa1_dfi,
      l_tab_state_cd_map_v  TYPE STANDARD TABLE OF zsd_state_cd_map,
      l_str_state_cd_map    TYPE zsd_state_cd_map,
      l_tab_vbrk_refdate    TYPE STANDARD TABLE OF ty_vbrk_refdate,
      l_str_vbrk_refdate    TYPE ty_vbrk_refdate,
      l_tab_vbfa            TYPE STANDARD TABLE OF ty_vbfa,
      l_str_vbfa            TYPE ty_vbfa.
DATA : l_tab_out_final TYPE STANDARD TABLE OF zdm_global.

DATA:
  l_var_tabix TYPE sy-tabix,
  l_var_skip  TYPE char1,
  cust_gstin  TYPE kna1-stcd3,
  ven_gstin   TYPE lfa1-stcd3.
*  BEGIN OF ty_head,
*    head(4096) TYPE c,
*  END OF ty_head,
*  tty_head  TYPE TABLE OF ty_head,
*
*  tty_dfies TYPE TABLE OF dfies.
*
*CONSTANTS: gc_drive_root                TYPE string VALUE 'C:',
*           gc_file_separator            TYPE string VALUE '/',
*           gc_folder_root               TYPE string VALUE 'OUTWARD SUPPLY',
*           gc_folder_unprocessed        TYPE string VALUE 'UNPROCESSED',
*           gc_path_for_al11             TYPE string VALUE '/sap/GSTData/OBD',
*
*           gc_folder_outward            TYPE string VALUE 'OUTWARD SUPPLY MAIN',
*           gc_folder_advrecd            TYPE string VALUE 'ADVANCE RECEIVED',
*           gc_folder_advadjst           TYPE string VALUE 'ADVANCE ADJUSTED',
*           gc_folder_invseries          TYPE string VALUE 'INVOICE SERIES',
*           gc_folder_b2c                TYPE string VALUE 'B2C',
*
*           gc_code_outward              TYPE string VALUE 'OCR',
*           gc_code_advrecd              TYPE string VALUE 'ARO',
*           gc_code_advadjst             TYPE string VALUE 'AAO',
*           gc_code_invseries            TYPE string VALUE 'INV',
*           gc_code_b2c                  TYPE string VALUE 'B2C',
*
*           gc_tablename_outward(30)     VALUE 'GT_FINAL_OUTWARD',
**  commented by MAdhu
*           gc_structure_outward(30)     VALUE 'YGSTOUTWARD01_ST',
*           gc_structure_outward1(30)    VALUE 'YGSTOUTWARD01_DIS',
*           gc_tablename_advrecd(30)     VALUE 'GT_FINAL_ADVRECD',
*           gc_structure_advrecd(30)     VALUE 'YGSTOUTWARD02_ST',
*           gc_structure_advrecd1(30)    VALUE 'YGSTOUTWARD02_DIS',
*           gc_tablename_advadjst(30)    VALUE 'GT_FINAL_ADVADJST',
*           gc_structure_advadjst(30)    VALUE 'YGSTOUTWARD02_ST',
*           gc_structure_advadjst1(30)   VALUE 'YGSTOUTWARD02_DIS',
*           gc_tablename_invseries(30)   VALUE 'GT_FINAL_INVSERIES',
*           gc_structure_invseries(30)   VALUE 'YGSTOUTWARD04_ST',
*           gc_tablename_b2c(30)         VALUE 'GT_FINAL_B2C',
*           gc_structure_b2c(30)         VALUE 'YGSTOUTWARD03_ST',
*           gc_structure_b2c1(30)        VALUE 'YGSTOUTWARD03_DIS',
*
*           gc_authorization_all(2)      VALUE '01',
*           gc_authorization_report(2)   VALUE '02',
*           gc_authorization_staging(2)  VALUE '03',
*           gc_authorization_download(2) VALUE '04'.

DATA: gt_final_outward TYPE STANDARD TABLE OF zdm_global,
      gl_final_outward TYPE zdm_global.

DATA: gt_final_outward1 TYPE STANDARD TABLE OF zdm_global,
      gl_final_outward1 TYPE zdm_global.

*      gt_final_temp            TYPE STANDARD TABLE OF ty_final_outward,
***      changed by Madhu
*      e_tab_rerurs             TYPE STANDARD TABLE OF ty_final_outward,
*      gt_final_outward1        TYPE STANDARD TABLE OF ty_final_outward,
**      gt_final_outward_ey      TYPE STANDARD TABLE OF ty_final_outward_ey,
*      gt_final_outward_ey1     TYPE STANDARD TABLE OF ty_final_outward_ey1,
**      ls_final_outward_ey      TYPE ty_final_outward_ey,
*      ls_final_outward_ey1     TYPE ty_final_outward_ey1,
**      ls_final_outward_temp_ey TYPE ty_final_outward_ey,

*      gt_final_inward          TYPE TABLE OF zdm_global,
*      gs_final_outward         TYPE ty_final_outward,
*      gs_outward01             TYPE ygstoutward01,
*      gt_outward01             TYPE TABLE OF ygstoutward01,
*      gt_final_advrecd         TYPE TABLE OF ty_advance_received,
*      gs_final_advrecd         TYPE ty_advance_received,
*      gt_final_advadjst        TYPE TABLE OF ty_advance_adjusted,
*      gs_final_advadjst        TYPE ty_advance_adjusted,
*      gt_final_invseries       TYPE TABLE OF ty_invoice_series,
*      gt_final_invseries1      TYPE TABLE OF ty_invoice_series,
*      gs_final_invseries       TYPE ty_invoice_series,
*      gt_final_b2c             TYPE TABLE OF ty_b2c,
*      gs_final_b2c             TYPE ty_b2c,
*      gt_head                  TYPE STANDARD TABLE OF ty_head,
*      gs_head                  TYPE ty_head,
*      gt_fcat                  TYPE slis_t_fieldcat_alv,
*      gs_fcat                  TYPE slis_fieldcat_alv,
*      gs_layo                  TYPE slis_layout_alv,
*      gs_gjahr                 TYPE gjahr,
*      gs_monat                 TYPE monat,
*      gs_line                  TYPE bapi3007_2,
*      gs_vari                  TYPE disvariant,
*      gv_folder                TYPE string,
*      gv_fname                 TYPE rlgrap-filename,
*      gv_full                  TYPE string,
*      gv_file                  TYPE string,
*      gv_path                  TYPE string,
*      gv_text                  TYPE char25.
*      gs_log                   TYPE zextractor_log,
*      gt_log                   TYPE TABLE OF zextractor_log.
*FIELD-SYMBOLS <fs_table> TYPE STANDARD TABLE.
*FIELD-SYMBOLS <fs_final> TYPE ty_invoice_series.

*RANGES: gr_budat FOR bkpf-budat.
*DATA: gv_get_live_data    TYPE flag,
*      gv_get_staging_data TYPE flag.

DATA: g_var_response      TYPE char1.

*********************************************Data Declaration for Fetching Data******************************************
*TYPES: BEGIN OF ty_vbrk,
*         vbeln TYPE vbeln_vf,
*         fkart TYPE fkart,
*         fktyp TYPE fktyp,
*         vbtyp TYPE vbtyp,
*         vtweg TYPE vtweg,
*         taxk1 TYPE vbrk-taxk1,
*         taxk2 TYPE vbrk-taxk2,
*         taxk3 TYPE vbrk-taxk3,
*         taxk4 TYPE vbrk-taxk4,
*         taxk5 TYPE vbrk-taxk5,
*         taxk6 TYPE vbrk-taxk6,
*         taxk7 TYPE vbrk-taxk7,
*         taxk8 TYPE vbrk-taxk8,
*         taxk9 TYPE vbrk-taxk9,
*         spart TYPE vbrk-spart,
*
*       END OF ty_vbrk,
*
*       BEGIN OF ty_vbrp,
*         vbeln      TYPE vbeln_vf,
*         posnr      TYPE posnr,
*         matnr      TYPE matnr,
*         arktx      TYPE arktx,
*         wkreg      TYPE wkreg,
*         augru_auft TYPE augru,
*         charg      TYPE vbrp-charg,
*       END OF ty_vbrp,
*
*       BEGIN OF ty_vbpa,
*         vbeln TYPE vbeln,
*         parvw TYPE parvw,
*         kunnr TYPE kunnr,
*       END OF ty_vbpa,
*
*       BEGIN OF ty_vbfa,
*         vbelv   TYPE vbelv,
*         vbeln   TYPE vbeln,
*         vbtyp_v TYPE vbtyp_v,
*       END OF ty_vbfa,
*       BEGIN OF ty_/obiz/zxp_shphd,
*         port_code      TYPE /obiz/zxp_shphd-port_code,
*         shp_bilno      TYPE /obiz/zxp_shphd-shp_bilno,
*         shp_bildt      TYPE /obiz/zxp_shphd-shp_bildt,
**         zzxp_shpbl_fob TYPE /obiz/zxp_shphd-zzxp_shpbl_fob,
*       END OF ty_/obiz/zxp_shphd,
*
*       BEGIN OF ty_t003,
*         blart TYPE blart,
*         koars TYPE koars_003,
*       END OF ty_t003,
*
*       BEGIN OF ty_kna1,
*         kunnr TYPE kunnr,
*         name1 TYPE name1_gp,
*         name2 TYPE name1_gp,
*         ort01 TYPE kna1-ort01,
*         pstlz TYPE kna1-pstlz,
*         stras TYPE kna1-stras,
*         adrnr TYPE adrnr,
*         regio TYPE regio,
*         land1 TYPE land1,
*         stcd3 TYPE stcd3,
*       END OF ty_kna1,
*       tty_kna1 TYPE TABLE OF ty_kna1,
*
*       BEGIN OF ty_mara,
*         matnr TYPE matnr,
*         mtart TYPE mtart,
*         matkl TYPE matkl,
*       END OF ty_mara,
*       tty_mara TYPE TABLE OF ty_mara,
*
*       BEGIN OF ty_makt,
*         matnr TYPE matnr,
*         maktx TYPE maktx,
*       END OF ty_makt,
*       tty_makt TYPE TABLE OF ty_makt,
*
*       BEGIN OF ty_bsis,
*         bukrs TYPE bsis-bukrs,
*         hkont TYPE bsis-hkont,
*         augdt TYPE bsis-augdt,
*         augbl TYPE bsis-augbl,
*         zuonr TYPE bsis-zuonr,
*         gjahr TYPE bsis-gjahr,
*         belnr TYPE bsis-belnr,
*         buzei TYPE bsis-buzei,
*         budat TYPE bsis-budat,
*         bldat TYPE bsis-bldat,
*       END OF ty_bsis,
*       tty_bsis TYPE TABLE OF ty_bsis,
*
*       BEGIN OF ty_1bbranch,
*         bukrs  TYPE j_1bbranch-bukrs,
*         branch TYPE j_1bbranch-branch,
*         name   TYPE j_1bbranch-name,
*         adrnr  TYPE j_1bbranch-adrnr,
*         gstin  TYPE j_1bbranch-gstin,
*         region TYPE adrc-region,
*       END OF ty_1bbranch,
*       tty_1bbranch TYPE TABLE OF ty_1bbranch,
*
*       BEGIN OF ty_bkpf,
*         bukrs     TYPE bukrs,
*         belnr     TYPE belnr_d,
*         gjahr     TYPE gjahr,
*         blart     TYPE blart,
*         bldat     TYPE bldat,
*         budat     TYPE budat,
*         cpudt     TYPE cpudt,
*         tcode     TYPE tcode,
*         xblnr     TYPE xblnr1,
*         usnam     TYPE usnam,
*         stblg     TYPE stblg,
*         stjah     TYPE stjah,
*         vatdate   TYPE vatdate,
*         xreversal TYPE xreversal,
*       END OF ty_bkpf,
*       tty_bkpf TYPE TABLE OF ty_bkpf,
*
*       BEGIN OF ty_bseg,
*         bukrs    TYPE bseg-bukrs,
*         belnr    TYPE bseg-belnr,
*         gjahr    TYPE bseg-gjahr,
*         buzei    TYPE bseg-buzei,
*         buzid    TYPE bseg-buzid,
*         augdt    TYPE bseg-augdt,
*         augbl    TYPE bseg-augbl,
*         bschl    TYPE bseg-bschl,
*         koart    TYPE bseg-koart,
*         umskz    TYPE bseg-umskz,
*         shkzg    TYPE bseg-shkzg,
*         gsber    TYPE bseg-gsber,
*         mwskz    TYPE bseg-mwskz,
*         dmbtr    TYPE bseg-dmbtr,
*         txgrp    TYPE bseg-txgrp,
*         ktosl    TYPE bseg-ktosl,
*         zuonr    TYPE bseg-zuonr,
*         kostl    TYPE bseg-kostl,
*         vbeln    TYPE bseg-vbeln,
*         saknr    TYPE bseg-saknr,
*         hkont    TYPE bseg-hkont,
*         kunnr    TYPE bseg-kunnr,
*         rebzg    TYPE bseg-rebzg,
*         rebzj    TYPE bseg-rebzj,
*         rebzz    TYPE bseg-rebzz,
*         rebzt    TYPE bseg-rebzt,
*         matnr    TYPE bseg-matnr,
*         werks    TYPE bseg-werks,
*         menge    TYPE bseg-menge,
*         meins    TYPE bseg-meins,
*         kidno    TYPE bseg-kidno,
*         bupla    TYPE bseg-bupla,
*         prctr    TYPE bseg-prctr,
*         taxps    TYPE bseg-taxps,
*         gst_part TYPE bseg-gst_part,
*         plc_sup  TYPE bseg-plc_sup,
*         hsn_sac  TYPE bseg-hsn_sac,
*       END OF ty_bseg,
*       tty_bseg TYPE TABLE OF ty_bseg,

*       BEGIN OF ty_zparam1,
*         param1 TYPE zparam-param1,
*         vkorg  TYPE zparam-vkorg,
*       END OF ty_zparam1,
*       tty_zparam1 TYPE TABLE OF ty_zparam1,

*       BEGIN OF ty_doccompress,
*         bukrs TYPE bukrs,
*         belnr TYPE bkpf-belnr,
*         gjahr TYPE bkpf-gjahr,
*       END OF ty_doccompress,
*       BEGIN OF ty_kunnrcompress,
*         kunnr TYPE kna1-kunnr,
*       END OF ty_kunnrcompress,
*       BEGIN OF ty_matnrcompress,
*         matnr TYPE matnr,
*       END OF ty_matnrcompress,
*       BEGIN OF ty_vbelncompress,
*         vbeln TYPE vbeln_vf,
*       END OF ty_vbelncompress,
*
*       BEGIN OF ty_bset,
*         bukrs TYPE bukrs,
*         belnr TYPE belnr_d,
*         gjahr TYPE gjahr,
*         buzei TYPE buzei,
*         mwskz TYPE mwskz,
*         txgrp TYPE txgrp,
*         shkzg TYPE shkzg,
*         hwbas TYPE hwbas_bses,
*         hwste TYPE hwste,
*         ktosl TYPE ktosl,
*         kschl TYPE kschl,
*         kbetr TYPE kbetr_tax,
*         bupla TYPE bupla,
*         taxps TYPE tax_posnr,
*       END OF ty_bset,
*       tty_bset TYPE TABLE OF ty_bset,
*
*       BEGIN OF ty_bsid_kunnr,
*         kunnr TYPE kunnr,
*       END OF ty_bsid_kunnr,
*
*       BEGIN OF ty_bseg_matnr,
*         matnr TYPE matnr,
*       END OF ty_bseg_matnr,
*       tty_bseg_matnr TYPE TABLE OF ty_bseg_matnr,
*
*       BEGIN OF ty_mlan,
*         matnr TYPE matnr,
*         aland TYPE aland,
*         taxim TYPE taxim1,
*       END OF ty_mlan,
*
*       BEGIN OF ty_bset_summary,
*         bukrs TYPE bukrs,
*         belnr TYPE belnr_d,
*         gjahr TYPE gjahr,
*         taxps TYPE taxps,
*       END OF ty_bset_summary,
*
*       BEGIN OF ty_bsec,
*         bukrs TYPE bukrs,
*         belnr TYPE belnr_d,
*         gjahr TYPE gjahr,
*         name1 TYPE bsec-name1,
*         name2 TYPE bsec-name2,
*         name3 TYPE bsec-name3,
*         name4 TYPE bsec-name4,
*         pstlz TYPE bsec-pstlz,
*         ort01 TYPE bsec-ort01,
*         regio TYPE regio,
*         stcd3 TYPE bsec-stcd3,
*         land1 TYPE bsec-land1,
*       END OF ty_bsec,
*
*       BEGIN OF ty_t604n,
*         steuc TYPE steuc,
*         text1 TYPE bezei60,
*       END OF ty_t604n,
*
*       BEGIN OF ty_skat,
*         ktopl TYPE ktopl,
*         saknr TYPE saknr,
*         txt50 TYPE txt50,
*       END OF ty_skat,
*
**       BEGIN OF ty_zparam,
**         param1 TYPE zparam1,
**         vkorg  TYPE zparam1,
**         vtweg  TYPE zparam1,
**         spart  TYPE zparam1,
**         loekz  TYPE zparam1,
**       END OF ty_zparam,
*
*       BEGIN OF ty_t001w,
*         werks      TYPE t001w-werks,
*         name1      TYPE t001w-name1,
*         name2      TYPE t001w-name2,
*         stras      TYPE t001w-stras,
*         pstlz      TYPE t001w-pstlz,
*         ort01      TYPE t001w-ort01,
*         regio      TYPE t001w-regio,
*         j_1bbranch TYPE t001w-j_1bbranch,
*       END OF ty_t001w,
*
*       BEGIN OF ty_j_1bbranch,
*         bukrs  TYPE j_1bbranch-bukrs,
*         branch TYPE j_1bbranch-branch,
*         gstin  TYPE j_1bbranch-gstin,
*       END OF ty_j_1bbranch.
*
*
*DATA: ls_bsis               TYPE ty_bsis,
*      lt_bsis               TYPE TABLE OF ty_bsis,
*      ls_1bbranch           TYPE ty_1bbranch,
*      lt_1bbranch           TYPE SORTED TABLE OF ty_1bbranch WITH UNIQUE KEY bukrs branch,
*      ls_t030k              TYPE j_1it030k,
*      lt_t030k              TYPE TABLE OF j_1it030k,
*      ls_bkpf               TYPE ty_bkpf,
*      lt_bkpf               TYPE TABLE OF ty_bkpf,
*      ls_bkpf_ref           TYPE ty_bkpf,
*      lt_bkpf_ref           TYPE TABLE OF ty_bkpf,
*      lt_bseg               TYPE TABLE OF ty_bseg,
*      ls_bseg               TYPE ty_bseg,
*      lt_bseg_d             TYPE TABLE OF ty_bseg,
*      ls_bseg_d             TYPE ty_bseg,
*      lt_bseg_t             TYPE TABLE OF ty_bseg,
*      ls_bseg_t             TYPE ty_bseg,
*      lt_bseg_w             TYPE TABLE OF ty_bseg,
*      ls_bseg_w             TYPE ty_bseg,
*      ls_bset               TYPE ty_bset,
*      lt_bset               TYPE TABLE OF ty_bset,
*      ls_bsec               TYPE ty_bsec,
*      lt_bsec               TYPE TABLE OF ty_bsec,
*      ls_mara               TYPE ty_mara,
*      lt_mara               TYPE SORTED TABLE OF ty_mara WITH UNIQUE KEY matnr,
*      ls_makt               TYPE ty_makt,
*      lt_makt               TYPE SORTED TABLE OF ty_makt WITH UNIQUE KEY matnr,
*      ls_kna1               TYPE ty_kna1,
*      lt_kna1               TYPE SORTED TABLE OF ty_kna1 WITH UNIQUE KEY kunnr,
*      ls_kna2               TYPE ty_kna1,
*      lt_kna2               TYPE SORTED TABLE OF ty_kna1 WITH UNIQUE KEY kunnr,
*      ls_vbrk               TYPE ty_vbrk,
*      lt_vbrk               TYPE SORTED TABLE OF ty_vbrk WITH UNIQUE KEY vbeln,
*      ls_vbpa               TYPE ty_vbpa,
*      lt_vbpa               TYPE SORTED TABLE OF ty_vbpa WITH NON-UNIQUE KEY vbeln parvw,
*      ls_vbfa               TYPE ty_vbfa,
*      lt_vbfa               TYPE SORTED TABLE OF ty_vbfa WITH NON-UNIQUE KEY vbelv vbeln vbtyp_v,
*      ls_mlan               TYPE ty_mlan,
*      lt_mlan               TYPE  TABLE OF ty_mlan,
*      ls_t001               TYPE t001,
*      ls_vbrp               TYPE ty_vbrp,
*      lt_vbrp               TYPE TABLE OF ty_vbrp,
*      lt_t005u              TYPE TABLE OF t005u,
*      ls_t005u              TYPE t005u,
*      ls_t003               TYPE ty_t003,
*      lt_t003               TYPE TABLE OF ty_t003,
**      ls_zparam1            TYPE ty_zparam1,
**      lt_zparam1            TYPE TABLE OF ty_zparam1,
*      ls_vbelncompress      TYPE ty_vbelncompress,
*      lt_vbelncompress      TYPE TABLE OF ty_vbelncompress,
*      ls_kunnrcompress      TYPE ty_kunnrcompress,
*      lt_kunnrcompress      TYPE TABLE OF ty_kunnrcompress,
*      ls_matnrcompress      TYPE ty_matnrcompress,
*      lt_matnrcompress      TYPE TABLE OF ty_matnrcompress,
*      ls_doccompress        TYPE ty_doccompress,
*      lt_doccompress        TYPE TABLE OF ty_doccompress,
*      ls_bset_summary       TYPE ty_bset_summary,
*      lt_bset_summary       TYPE TABLE OF ty_bset_summary,
*      lt_t604n              TYPE TABLE OF ty_t604n,
*      ls_t604n              TYPE ty_t604n,
*      lt_t001w              TYPE TABLE OF ty_t001w,
*      ls_t001w              TYPE ty_t001w,
*      lt_j_1bbranch         TYPE TABLE OF ty_j_1bbranch,
*      ls_j_1bbranch         TYPE ty_j_1bbranch,
*      lt_skat               TYPE TABLE OF ty_skat,
*      ls_skat               TYPE ty_skat,
*      ls_/obiz/zxp_shphd    TYPE ty_/obiz/zxp_shphd,
*
*      lv_structurename(30),
*
*      ls_doctype            TYPE zdmdoctype,
*      lt_doctype            TYPE TABLE OF zdmdoctype,
**      ls_statecode          TYPE ZEI_STATE_CODE, "zgstnstatecode,
**      lt_statecode          TYPE SORTED TABLE OF ZEI_STATE_CODE WITH NON-UNIQUE KEY regio, "zgstnstatecode
**      ls_supplytype         TYPE zgstnsupplytype,
**      lt_supplytype         TYPE TABLE OF zgstnsupplytype,
**      ls_transkey           TYPE zgstnttranskey,
**      lt_transkey           TYPE TABLE OF zgstnttranskey,
**      ls_tvaut              TYPE tvaut,
**      lt_tvaut              TYPE TABLE OF tvaut,
*
**      ls_outward01          TYPE ygstoutward01,
**      lt_outward01          TYPE TABLE OF ygstoutward01,
*      lt_final_outward      TYPE STANDARD TABLE OF ty_final_outward,
*      ls_final_outward      TYPE ty_final_outward,
*      ls_final_outward_temp TYPE ty_final_outward,
*      ls_final_out          TYPE ty_final_outward,
**      ls_zparam             TYPE ty_zparam,
**      lt_zparam             TYPE TABLE OF ty_zparam,
*      ls_final_inward       TYPE  zdm_global,
**        lt_final_inward TYPE STANDARD TABLE OF ygstinward01,
*      """"""""""""""""""""""""""""Supply type"""""""""""""""""""""""
*      lv_taxim              TYPE taxim1,
*      lv_taxk1              TYPE vbrk-taxk1,
*      lv_taxk2              TYPE vbrk-taxk2,
*      lv_taxk3              TYPE vbrk-taxk3,
*      lv_taxk4              TYPE vbrk-taxk4,
*      lv_taxk5              TYPE vbrk-taxk5,
*      lv_taxk6              TYPE vbrk-taxk6,
*      lv_taxk7              TYPE vbrk-taxk7,
*      lv_taxk8              TYPE vbrk-taxk8,
*      lv_taxk9              TYPE vbrk-taxk9,
*      lv_vtweg              TYPE vbrk-vtweg,
*      lv_blart              TYPE blart,
*      lv_mwskz              TYPE mwskz,
*      lv_fkart              TYPE fkart,
*      lv_shkzg              TYPE shkzg,
*      lv_land1              TYPE char03,
*      lv_inward             TYPE char1,
*      lv_batch              TYPE char25,
*      lv_bldat              TYPE bldat,
*      lv_success_flag       TYPE c,
*      lv_hsn_sac            TYPE bseg-hsn_sac,
*      lv_matnr              TYPE matnr,
*      lv_werks              TYPE werks_d,
*      lv_netwr              TYPE netwr,
*      lv_mwsbp              TYPE mwsbp,
*      lv_char5              TYPE char5,
*      lv_vbeln_c            TYPE vbeln,
**      lv_port_code          TYPE zportcode,
*      lv_vgbel              TYPE vgbel,
*      lv_shippingbilldate   TYPE bldat,
*      lv_line_count(4)      TYPE n.
*
**DATA : lt_uom    TYPE STANDARD TABLE OF zgst_uom,
**       ls_uom    TYPE zgst_uom,
*
** DATA : lt_reason TYPE STANDARD TABLE OF zgst_reason,
**       ls_reason TYPE zgst_reason.
*
*RANGES: lr_ktosl FOR j_1it030k-ktosl,
*        lr_blart FOR bkpf-blart.
*FREE: gt_final_outward,gt_outward01.

DATA: lv_sub_flag TYPE c.
*
DATA:lv_var_response TYPE char1.
****Variables************************************************************
DATA : l_var_cnt  TYPE i,
       l_var_text TYPE string.
***Reference************************************************************
DATA : l_rcl_header      TYPE REF TO cl_salv_form_element,
       l_rcl_grid_layout TYPE REF TO cl_salv_form_layout_grid,
       l_rcl_label       TYPE REF TO cl_salv_form_label,
       l_rcl_text        TYPE REF TO cl_salv_form_text.
************************************************************************

DATA: lt_header     TYPE slis_t_listheader,
      wa_header     TYPE slis_listheader,
      ls_header     TYPE slis_listheader,
      t_line        LIKE wa_header-info,
      ld_lines      TYPE i,
      ld_linesc(10) TYPE c.
