*&---------------------------------------------------------------------*
*&  Include           ZGSP_GL_GENRATOR_TOP
*&---------------------------------------------------------------------*
TABLES:bkpf,bseg.

TYPE-POOLS: slis.                                 "ALV Declarations
*Data Declaration
*----------------
TYPES: BEGIN OF t_final,
         business_place  TYPE bseg-bupla,
         document_no     TYPE bkpf-belnr,
         gl_account      TYPE bseg-hkont,
         location_gstin  TYPE j_1bbranch-gstin,
         account_type    TYPE bseg-koart,

         gl_account_desc TYPE skat-txt20,
         document_type   TYPE char10,

         document_date   TYPE bkpf-bldat,
         place_supply    TYPE bseg-plc_sup,
         debit_credit    TYPE bseg-shkzg,
         reference       TYPE bkpf-xblnr,
         assignment      TYPE bseg-zuonr,
         text            TYPE bseg-sgtxt,
         postingkey      TYPE bseg-bschl,
         posting_date    TYPE bkpf-budat,
         currency        TYPE bseg-pswsl,
         amount          TYPE bseg-hwbas,
         customer_code   TYPE bseg-lifnr,
         customer_gst    TYPE kna1-stcd3,
         customer_name   TYPE lfa1-name1,
         tcode           TYPE bkpf-tcode,
         hsn             TYPE bseg-hsn_sac,
         custom1         TYPE char100,
         custom2         TYPE char100,
         custom3         TYPE char100,
         custom4         TYPE char100,
         custom5         TYPE char100,
         custom6         TYPE char100,
         custom7         TYPE char100,
         custom8         TYPE char100,
         custom9         TYPE char100,
         custom10        TYPE char100,
       END OF t_final.

TYPES: BEGIN OF t_final1,
         business_place  TYPE bseg-bupla,
         location_gstin  TYPE j_1bbranch-gstin,
         account_type    TYPE bseg-koart,
         gl_account      TYPE bseg-hkont,
         gl_account_desc TYPE skat-txt50,
         document_type   TYPE char10,
         document_no     TYPE bkpf-belnr,
         document_date   TYPE bkpf-bldat,
         place_supply    TYPE bseg-plc_sup,
         debit_credit    TYPE bseg-shkzg,
         reference       TYPE bkpf-xblnr,
         assignment      TYPE bseg-zuonr,
         text            TYPE bseg-sgtxt,
         postingkey      TYPE bseg-bschl,
         posting_date    TYPE bkpf-budat,
         currency        TYPE bseg-pswsl,
         amount          TYPE bseg-hwbas,
         customer_code   TYPE bseg-lifnr,
         customer_gst    TYPE kna1-stcd3,
         customer_name   TYPE lfa1-name1,
         tcode           TYPE bkpf-tcode,
         hsn             TYPE bseg-hsn_sac,
         custom1         TYPE char100,
         custom2         TYPE char100,
         custom3         TYPE char100,
         custom4         TYPE char100,
         custom5         TYPE char100,
         custom6         TYPE char100,
         custom7         TYPE char100,
         custom8         TYPE char100,
         custom9         TYPE char100,
         custom10        TYPE char100,
       END OF t_final1,


       BEGIN OF ty_bkpf,
         bukrs     TYPE bkpf-bukrs,
         belnr     TYPE bkpf-belnr,
         gjahr     TYPE bkpf-gjahr,
         blart     TYPE bkpf-blart,
         bldat     TYPE bkpf-bldat,
         budat     TYPE bkpf-budat,
         monat     TYPE bkpf-monat,
         xreversal TYPE bkpf-xreversal,
         xblnr_alt TYPE bkpf-xblnr_alt,
         stblg     TYPE bkpf-stblg,
         xblnr     TYPE bkpf-xblnr,
         tcode     TYPE bkpf-tcode,
       END OF ty_bkpf,

       BEGIN OF ty_bseg,
         bukrs   TYPE bseg-bukrs,
         belnr   TYPE bseg-belnr,
         gjahr   TYPE bseg-gjahr,
         buzei   TYPE bseg-buzei,
         txgrp   TYPE bseg-txgrp,
         hkont   TYPE bseg-hkont,
         kunnr   TYPE bseg-kunnr,
         lifnr   TYPE bseg-lifnr,
         plc_sup TYPE bseg-plc_sup,
         hsn_sac TYPE bseg-hsn_sac,
         bupla   TYPE bseg-bupla,
         buzid   TYPE bseg-buzid,
         koart   TYPE bseg-koart,
         dmbtr   TYPE bseg-dmbtr,
         shkzg   TYPE bseg-shkzg,
         zuonr   TYPE bseg-zuonr,
         sgtxt   TYPE bseg-sgtxt,
         bschl   TYPE bseg-bschl,
         pswsl   TYPE bseg-pswsl,
       END OF ty_bseg,
       BEGIN OF ty_bseg_tem,
         bukrs   TYPE bseg-bukrs,
         belnr   TYPE bseg-belnr,
         gjahr   TYPE bseg-gjahr,
         hkont   TYPE bseg-hkont,
         txgrp   TYPE bseg-txgrp,
         buzei   TYPE bseg-buzei,
         kunnr   TYPE bseg-kunnr,
         lifnr   TYPE bseg-lifnr,
         plc_sup TYPE bseg-plc_sup,
         hsn_sac TYPE bseg-hsn_sac,
         bupla   TYPE bseg-bupla,
         buzid   TYPE bseg-buzid,
         koart   TYPE bseg-koart,
         dmbtr   TYPE bseg-dmbtr,
         shkzg   TYPE bseg-shkzg,
         zuonr   TYPE bseg-zuonr,
         sgtxt   TYPE bseg-sgtxt,
         bschl   TYPE bseg-bschl,
         pswsl   TYPE bseg-pswsl,
         augbl   TYPE bseg-augbl,
       END OF ty_bseg_tem,


       BEGIN OF ty_bset,
         bukrs TYPE bset-bukrs,
         belnr TYPE bset-belnr,
         gjahr TYPE bset-gjahr,
         buzei TYPE bset-buzei,
         hkont TYPE bset-hkont,
         shkzg TYPE bset-shkzg,
         hwste TYPE bset-hwste,
         txgrp TYPE bset-txgrp,
         hwbas TYPE bset-hwbas,
       END OF ty_bset.




DATA: it_bkpf         TYPE STANDARD TABLE OF ty_bkpf,
      wa_bkpf         TYPE ty_bkpf,
      it_bseg         TYPE STANDARD TABLE OF ty_bseg,
      it_bseg_tmp     TYPE STANDARD TABLE OF ty_bseg_tem,
      it_bseg_tmp_d   TYPE STANDARD TABLE OF ty_bseg,
      it_bseg_tmp_k   TYPE STANDARD TABLE OF ty_bseg,
      it_bseg_tmp_l   TYPE STANDARD TABLE OF ty_bseg,
      it_bseg_tmp_pos TYPE STANDARD TABLE OF ty_bseg,
      lt_lfa1         TYPE STANDARD TABLE OF lfa1,
      ls_lfa1         TYPE lfa1,
      lt_kna1         TYPE STANDARD TABLE OF kna1,
      ls_kna1         TYPE kna1,
      wa_bseg         TYPE ty_bseg,
      ls_bseg_tmp     TYPE ty_bseg_tem,
      ls_bseg_tmp_d   TYPE ty_bseg,
      ls_bseg_tmp_k   TYPE ty_bseg,
      ls_bseg_tmp_l   TYPE ty_bseg,
      ls_bseg_tmp_pos TYPE ty_bseg,
      it_j_1bbranch   TYPE STANDARD TABLE OF j_1bbranch,
      lt_tab_skat     TYPE STANDARD TABLE OF skat,
      wa_j_1bbranch   TYPE j_1bbranch,
      ls_skat         TYPE skat,
      it_final1       TYPE STANDARD TABLE OF t_final,
      wa_final1       TYPE t_final,
      wa_final_t      TYPE t_final,
      it_final        TYPE STANDARD TABLE OF t_final1,
      wa_final        TYPE t_final1.

DATA : lt_bset      TYPE STANDARD TABLE OF ty_bset,
       ls_bset      TYPE ty_bset,
       ls_bset_temp TYPE ty_bset.

*ALV data declarations
DATA: fieldcatalog TYPE slis_t_fieldcat_alv WITH HEADER LINE,
      gd_tab_group TYPE slis_t_sp_group_alv,
      gd_layout    TYPE slis_layout_alv,
      gd_repid     LIKE sy-repid.
